"use client";
import {useEffect,useState,FormEvent} from 'react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {Button} from '@/components/ui/button';
import {ArrowRight,Plus,FileText,RefreshCw,ShieldCheck} from 'lucide-react';
import {Turnstile} from './TurnstileWidget';
export function Participation({onUpload,refreshKey=0}:{onUpload:()=>void;refreshKey?:number}){
 const [choice,setChoice]=useState(''),[phone,setPhone]=useState(''),[resident,setResident]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[done,setDone]=useState(false);
 const [tsToken,setTsToken]=useState('');
 const [stats,setStats]=useState<any>(null),[error,setError]=useState(false),[wall,setWall]=useState<any[]>([]),[wallError,setWallError]=useState(false);
 async function refresh(){try{const r=await fetch('/api/votes');if(!r.ok)throw Error();setStats(await r.json());setError(false)}catch{setError(true)}try{const r=await fetch('/api/evidence');if(!r.ok)throw Error();setWall((await r.json()).items);setWallError(false)}catch{setWallError(true)}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,30000);return()=>clearInterval(timer)},[refreshKey]);
 async function vote(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');if(!tsToken){setMessage('请完成人机校验。');setBusy(false);return}try{const r=await fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,choice,resident,consent,turnstileToken:tsToken})});const d=await r.json();if(!r.ok)throw Error(d.error);setPhone('');setDone(true);refresh()}catch(e){setMessage(e instanceof Error?e.message:'提交失败，请稍后再试。')}finally{setBusy(false)}}
 return <><section className="section poll" id="vote"><div className="section-heading"><h2>车位怎么划，<span>居民来表态。</span></h2><p>两种立场，同等展示<br/>自愿参与 · 按手机号去重</p></div><p className="poll-question">您是否支持在建材路本次争议路段增加机动车路侧停车位？</p><div className="poll-layout"><form onSubmit={vote} className="poll-form">{done?<div className="vote-success"><ShieldCheck size={36}/><h3>已计入你的意见</h3><p>该手机号本次不再重复计票。公开结果中不会出现手机号。</p></div>:<><RadioGroup value={choice} onValueChange={setChoice} aria-label="是否支持增加车位" className="vote-options">{[['support','支持增加车位'],['oppose','不支持增加车位']].map(([v,t])=><label className={'vote-option '+(choice===v?'selected':'')} key={v}><RadioGroupItem value={v} id={'vote-'+v}/><span>{t}</span></label>)}</RadioGroup><label className="phone-label" htmlFor="vote-phone">手机号 <small>（仅作民意统计去重）</small></label><input id="vote-phone" value={phone} onChange={e=>setPhone(e.target.value)} required autoComplete="off" inputMode="tel" type="tel" maxLength={20} placeholder="请输入本人中国大陆手机号"/><div className="check-row"><Checkbox id="resident" checked={resident} onCheckedChange={v=>setResident(v===true)}/><label htmlFor="resident">我确认是附近居民，并使用本人手机号参与。</label></div><div className="check-row"><Checkbox id="vote-consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="vote-consent">我已阅读下方隐私与计票说明，同意处理手机号用于本次去重。</label></div><Turnstile onToken={setTsToken} className="cf-turnstile-host" />{message&&<p role="alert" className="error">{message}</p>}<Button type="submit" disabled={busy||!choice||!resident||!consent} className="vote-submit">{busy?'正在提交…':'提交我的意见'}<ArrowRight size={17}/></Button></>}<details className="poll-rules"><summary>隐私与计票说明</summary><p>手机号严格保密，仅作本次民意统计去重，不展示、不营销、不与证据材料关联。服务端仅保留带密钥的去重指纹，不保存号码明文。每个手机号只计一票，两种立场采用相同规则，不因立场不同删除票数。</p><p>暂未进行短信验证码或居住身份核验，不能完全排除冒用号码。结果为自愿参与的网络意见征集，不代表全体居民，不作为正式选举或法定表决。统计自本功能开放起累计，页面每30秒刷新。</p></details></form><div className="poll-results"><div className="results-title"><h3>公开计票</h3><button className="text-link" onClick={refresh} aria-label="刷新计票"><RefreshCw size={16}/>刷新</button></div>{error?<p role="status" className="notice">统计暂时无法更新{stats?'，以下为上次获取结果':'，请稍后重试'}。</p>:null}{stats?<><p className="vote-total"><strong>{stats.total}</strong><span>份去重后的意见</span></p>{[['support','支持增加车位'],['oppose','不支持增加车位']].map(([key,label])=>{const pct=stats.total?Math.round(stats[key]/stats.total*1000)/10:0;return <div className="result-row" key={key}><div><span>{label}</span><span><b>{stats[key]}</b> 票 · {pct}%</span></div><div className="result-track" role="meter" aria-label={label+'占比'} aria-valuemin={0} aria-valuemax={100} aria-valuenow={pct}><span style={{width:pct+'%'}}/></div></div>})}<small>统计获取时间：{new Date(stats.updatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}（北京时间）</small></>:!error?<p>正在读取实际票数…</p>:null}<div className="survey-limit"><strong>未短信核验 · 自愿样本</strong><p>支持与反对都值得被听见。票数表达参与者意愿，划线是否合理仍须结合现场条件与法定要求。</p></div></div></div></section>
 <section className="section photo-wall" id="wall"><div className="section-heading"><h2>现场什么样，<span>材料直接展示。</span></h2><button onClick={onUpload} className="primary">上传附件并发布 <Plus size={18}/></button></div><p className="section-note">居民提交后直接展示。附件必须上传；发布者须先遮挡手机号、人脸、车牌、住址等个人信息。页面展示不等同于本站已独立核实全部事实，请勿据此认定个人责任。</p>{wallError?<p className="notice">证据墙暂时无法更新，请稍后刷新。</p>:null}{wall.length?<div className="wall-grid">{wall.map(item=><article className="wall-card" key={item.id}>{item.files.length?<div className="wall-media">{item.files[0].type.startsWith('image/')?<a href={item.files[0].url} target="_blank" rel="noreferrer"><img src={item.files[0].url} alt={item.title} loading="lazy"/></a>:item.files[0].type.startsWith('video/')?<video controls preload="metadata" playsInline src={item.files[0].url}/>:<div className="wall-text-icon"><FileText size={38}/><a href={item.files[0].url}>查看附件</a></div>}</div>:null}<div className="wall-card-body"><span className="red-kicker">居民提交 · 未经独立核实</span><h3>{item.title}</h3><p className="wall-description">{item.content}</p><small>{item.location||'位置未注明'} · {item.event_date||'发生时间未注明'}</small>{item.files.length>1&&<div className="wall-attachments">{item.files.slice(1).map((f:any,i:number)=><a href={f.url} key={i} target="_blank" rel="noreferrer">附件 {i+2}：{f.name}</a>)}</div>}<small>发布：{new Date(item.created_at).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'})}</small></div></article>)}</div>:!wallError?<div className="wall-empty"><h3>等待第一份居民现场材料。</h3><p>提交至少一个图片、视频、录音或文件，发布后立即展示。</p><button onClick={onUpload} className="text-link">提交并展示 <Plus size={18}/></button></div>:null}</section></>;
}
