import {database} from '@/db/raw';
import {isReviewer,crossSite,reviewerEmail} from '@/lib/review';
export async function GET(request:Request){if(!(await isReviewer(request)))return Response.json({error:'仅专题管理者可查看。'},{status:403});try{const r=await database().prepare('SELECT * FROM materials ORDER BY created_at DESC LIMIT 100').all();return Response.json({items:r.results.map((row:any)=>({...row,files:JSON.parse(row.files).map((f:any,i:number)=>({name:f.name,type:f.type,url:'/api/media?id='+row.id+'&index='+i}))}))},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'读取失败。'},{status:503})}}
export async function POST(request:Request){if(!(await isReviewer(request))||crossSite(request))return Response.json({error:'无权操作。'},{status:403});try{const d=await request.json() as any;if(!['published','pending','rejected'].includes(d.status)||!d.id)return Response.json({error:'参数不正确。'},{status:400});const row=await database().prepare('SELECT consent,title,content,location FROM materials WHERE id=?').bind(d.id).first<any>();if(!row)return Response.json({error:'材料不存在。'},{status:404});if(d.status==='published'&&(row.consent!==1||d.checked!==true))return Response.json({error:'仅可发布用户已授权且完成隐私核查的材料。'},{status:400});const title=String(d.title||'').trim(),content=String(d.content||'').trim(),location=String(d.location||'').trim();if(!title||title.length>120||content.length<5||content.length>10000||location.length>200)return Response.json({error:'请填写有效标题和描述。'},{status:400});
const editor=await reviewerEmail(request)||'unknown';
const revisions:any[]=[];if(row.title!==title)revisions.push({field:'title',before:row.title,after:title});if(row.content!==content)revisions.push({field:'content',before:row.content,after:content});if(row.location!==location)revisions.push({field:'location',before:row.location,after:location});revisions.push({field:'status',before:'',after:d.status});
const id=crypto.randomUUID();
const now=new Date().toISOString();
await database().prepare('UPDATE materials SET status=?,title=?,content=?,location=?,updated_at=?,editor_id=? WHERE id=?').bind(d.status,title,content,location,now,editor,d.id).run();
for(const r of revisions){await database().prepare('INSERT INTO material_revisions (id,material_id,editor_id,editor_label,field,before,after,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,d.id,editor,editor,r.field,r.before,r.after,now).run()}
return Response.json({ok:true});}catch{return Response.json({error:'保存失败。'},{status:503})}}
